// USERS TYPE
export const RECEIVE_USERS = 'RECEIVE_USERS';

// QUESTIONS TYPES
export const RECEIVE_QUESTIONS = 'RECEIVE_QUESTIONS';
export const ADD_QUESTION = 'ADD_QUESTION';
export const ADD_QUESTION_RESPONSE = 'ADD_QUESTION_RESPONSE';

// AUTHED USER TYPE
export const SET_AUTHED_USER = 'SET_AUTHED_USER';
