// USERS TYPE
export const RECEIVE_USERS = 'RECEIVE_USERS';
export const ALLOCATE_ANSWER_TO_USER = 'ALLOCATE_ANSWER_TO_USER';
export const ALLOCATE_QUESTION_TO_USER = 'ALLOCATE_QUESTION_TO_USER';

// QUESTIONS TYPES
export const RECEIVE_QUESTIONS = 'RECEIVE_QUESTIONS';
export const ADD_QUESTION = 'ADD_QUESTION';
export const ADD_QUESTION_RESPONSE = 'ADD_QUESTION_RESPONSE';

// AUTHED USER TYPE
export const SET_AUTHED_USER = 'SET_AUTHED_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const SET_CALL_BACK_LINK = 'SET_CALL_BACK_LINK';
